Contributing to open-source in order to get started with the organisation
CodingContributorsLair/Get-Started-Here pull request #60
Opened 2024-06-09 12:07 UTC by SUDEEP-M-SHETTY

2024-06-11 21:28 UTC, AvidCoder101 requested changes
Hi @SUDEEP-M-SHETTY your first commit which was your name addition to CONTRIBUTORS.md was perfect, however, you do seem to have edited the .all-contributors.src file and the README.md file, which both of them is done by a bot _after_ I merge your PR. Please could you delete the last two commits, and then I can merge your PR? Thanks 🙂

2025-04-20 23:45 UTC, merged

2025-04-20 23:46 UTC, AvidCoder101 commented
@SUDEEP-M-SHETTY I have sent you an invite to the organisation

2025-04-20 23:46 UTC, AvidCoder101 commented
@all-contributors please add @SUDEEP-M-SHETTY for content

2025-05-02 11:30 UTC, SUDEEP-M-SHETTY commented
> @SUDEEP-M-SHETTY I have sent you an invite to the organisation

Might have missed the invite, cloud you send it again. Thanks!😄

2025-05-04 03:36 UTC, AvidCoder101 commented
@SUDEEP-M-SHETTY sorry for that, I've resent the invitation, hopefully it should work this time 😄

2025-05-04 05:26 UTC, SUDEEP-M-SHETTY commented
> @SUDEEP-M-SHETTY sorry for that, I've resent the invitation, hopefully it should work this time 😄

Received the invite, thanks! 🙌